config/routes.rb
Rails.application.routes.draw do
get "signup", to: "users#new", as: "signup"
get "login", to: "sessions#new", as: "login"
get "logout", to: "sessions#destroy", as: "logout"

  resources :users
  get "/sessions/current", to: "sessions#destroy"
  
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/trails", to: "trails#index"
  get "/trails/:trail_id", to: "trails#show", as: "trail"
  post "/nodes/check_answer", to: "nodes#checkanswer", as: "check_answer"
  
  root "trails#index"

  get "/admin/trails", to: "trails#admin_index", as: "admin"
  get "/admin/trails/:trail_id", to: "trails#admin_show", as: "admin_show"
  post "/admin/trails", to: "trails#trail_create", as: "trail_create"
  get "/admin/trails/nodes/:node_id", to: "nodes#destroy", as: "node_destroy"

  get "admin/update/:trail_id", to: "trails#admin_show_update", as: "admin_show_update"
  post "admin/update/:trail_id", to: "nodes#update", as: "node_update" 


  post "/admin/trails/:trail_id", to: "trails#node_create", as: "node_create"


   

end

app/models/trail.rb
class Trail < ApplicationRecord
  has_many :nodes
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  
  def index
  end

  def show
    if current_user == nil
      flash.alert = "You need to be logged in."
      redirect_to root_url
    else
      @trail = Trail.find(params[:trail_id])
      @current_node = @trail.nodes.select { |node| !current_user.completed_nodes.map { |completed_node| completed_node.node_id }.include?(node.id) }.first
      @trail_progress = @trail.nodes.select { |node| current_user.completed_nodes.map { |completed_node| completed_node.node_id }.include?(node.id) }.count
    end

  end

  def nodeprogress
    @nodeprogress = @trail.nodes.select { |node| current_user.completed_nodes.map { |completed_node| completed_node.node_id }.include?(node.id) }.count
  end

  def admin_index
    if !current_user.admin
        redirect_to root_url
    end

    @trails = Trail.all 
  end

  def admin_show
    if !current_user.admin
          redirect_to root_url
    end

    @trail = Trail.find(params[:trail_id])
    @node = Node.new
  end

  def trail_new
    @trail = Trail.new
  end

  def trail_create
    @trail = Trail.new(trail_params)

    if @trail.save
      redirect_to admin_url, notice: "Trail created!"
    else
      render "trail_new"
    end
  end 


  def node_create
    @node = Node.new(node_params)
    
    if @node.save
      redirect_to admin_show_url, notice: "Node created!"
    else 
      redirect_to admin_show_url
    end
  end

  def image_classify
    require "onnxruntime"
    require "mini_magick"

    img = MiniMagick::Image.open("images/bears.jpg")
    pixels = img.get_pixels

    model = OnnxRuntime::Model.new("lib/model.onnx")
    result = model.predict({"inputs" => [pixels]})

    @num_detections = result["num_detections"]
    @detectionClasses = result["detection_classes"]
  end




  private 
  
  def trail_params
    params.require(:trail).permit(:name)
  end

  def node_params
    params.require(:node).permit(:trail_id, :question, :answer, :hint, :image_question)
  end


 

end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/trails/admin_index.html.erb
<header>
<h1> ADMIN CONTROLS </h1>
 <%= stylesheet_link_tag 'trails.css' %>

</header>



<body>

<h2>Create New Trail:</h2>

<%= form_with model: Trail.new, url: "/admin/trails" do |form| %>
    <createtrail>
    <%= form.label :Name_of_Trail %><br>
    <%= form.text_field :name %>
    </createtrail>


    <div>
    <%= form.submit %>
    </div>
<% end %>







<% Trail.all.each do | t | %>
  <div> <%= link_to(t.name,admin_show_path(t), class: "trail-link")%> </div>
  
  <div> Nodes: </div>
  <% t.nodes.each do | node | %>
  <div style="margin-left:9px;"> <%= node.id %> - <%= node.question%> </div>
  <% end %>
<% end %>



</body>

app/views/trails/admin_show.html.erb
<h1>Amend Nodes Panel</h1>
<%= stylesheet_link_tag 'trails.css' %>

<trailname>
  <h1>Node:  <%= @trail.name%>  </h1>
</trailname>

<body>
 <node_id> Node ID | Question | Answer:
    <% @trail.nodes.each do | node | %>
      <div style="margin-left:9px;"> ID: <%= node.id %> | Question: "<%= node.question%>" | Answer: "<%= node.answer %>"| <%= link_to "Destroy", node_destroy_path(node.id), data: { confirm: "Are you sure?" } %></div></div>
    
    <% end %>
  
</node_id>

<div>
    <% @trail.nodes.each do |node| %>
        <div>Amend ID: <%= node.id %></div>
        <div class="toggle-update-form-button" data-node-id="<%= node.id %>">Toggle form</div>
        <div id="update-form-<%= node.id %>" class="hidden node-form-wrapper">
            <%= form_with model: @node, :url => node_update_path do |form| %>


  <div>
    <%= form.hidden_field :node_id, value: node.id%>
    
   </div>

   <div> 
    <%= form.label :Question %><br>
    <%= form.text_area :question %>
   
   
  </div>

  <div>
    
    <%= form.label :Answer %><br>
    <%= form.text_area :answer %>
    
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

        </div>
    <% end %>
</div>
  




<h3>Create a new node in trail:</h3>
<button type="button" id="create-node-button">Create</button> 


<createnode id= "createnode" class="hidden">
<%= form_with model: Node.new, url:"/admin/trails/" + @trail.id.to_s do |form| %>




  <div>
    <%= form.hidden_field :trail_id, value: @trail.id %>
    <%= form.label :Question %><br>
    <%= form.text_area :question %>
  </div>

  <div>
    
    <%= form.label :Answer %><br>
    <%= form.text_area :answer %>
    
  </div>

  <div>
     <%= form.label :Hint_Image_URL %><br>
    <%= form.text_area :image %>
  
  </div>

  <div>
  Image classify question:
    <%= form.select :image_question, ['false', 'true']%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

</createnode>



</body>

<script>
document.getElementById("create-node-button").addEventListener("click", function() {
  document.getElementById("createnode").classList.toggle("hidden");
  
});
</script>

<script>
    document.querySelectorAll(".toggle-update-form-button").forEach(function(button) {
        button.addEventListener("click", function(e) {
            document.getElementById(`update-form-${e.target.dataset.nodeId}`).classList.toggle("hidden");
        });
        const formToShow = 
        document.getElementById
    });
</script>

app/views/trails/admin_show_update.html.erb
<h1>Amend Nodes Panel</h1>
<%= stylesheet_link_tag 'trails.css' %>

<trailname>
  <h1>Node:  <%= @trail.name%>  </h1>
</trailname>

<body>
 <node_id> Node ID | Question | Answer:
    <% @trail.nodes.each do | node | %>
      <div style="margin-left:9px;"> ID: <%= node.id %> | Question: "<%= node.question%>" | Answer: "<%= node.answer %>"</div></div>
    <% end %>
</node_id>
  
 


<h3>Adjust nodes in trail:</h3>
<button type="button" id="create-node-button">Create</button> 
<button type="button" id="amend-node-button">Amend</button> 
<button type="button" id="create-node-button">Delete</button> 

<createnode id= "createnode" class="hidden">
<%= form_with model: Node.new, url:"/admin/trails/" + @trail.id.to_s do |form| %>




  <div>
    <%= form.hidden_field :trail_id, value: @trail.id %>
    <%= form.label :Question %><br>
    <%= form.text_area :question %>
  </div>

  <div>
    
    <%= form.label :Answer %><br>
    <%= form.text_area :answer %>
    
  </div>

  <div>
     <%= form.label :Hint_Image_URL %><br>
    <%= form.text_area :image %>
  
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

</createnode>



<%= form_with model: @nodes, url: node_update_path do |form| %>


  <div>
    <%= form.hidden_field :trail_id, value: @trail.id %>
     <%= form.label :Node_ID %><br>
    <%= form.text_area :node_id %>
   </div>

   <div> 
    <%= form.label :Question %><br>
    <%= form.text_area :question %>
   
   
  </div>

  <div>
    
    <%= form.label :Answer %><br>
    <%= form.text_area :answer %>
    
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>












</body>

<script>
document.getElementById("create-node-button").addEventListener("click", function() {
  document.getElementById("createnode").classList.toggle("hidden");
  
});
</script>

<script>
document.getElementById("amend-node-button").addEventListener("click", function() {
  document.getElementById("amendnode").classList.toggle("hidden");
  
});
</script>

app/views/trails/index.html.erb

<body>


<div class="row py-3">
  <div class="col-2"></div>
  <div class="col-8 bg-light rounded" >
      <h2>
        <div class="row d-flex justify-content-center border">Trails Available:</div>
      </h2>
    
      <div class="d-flex justify-content-center">
        </div>
      <div class="row d-flex justify-content-center"></div>
      <div class="row d-flex justify-content-center">
        <h4>
         
        </h4>
      </div>

<% Trail.all.each do | t | %>
  <div> <%= link_to(t.name,trail_path(t), class: "trail-link")%> </div>
  
  <div style="margin-left:9px;">Number of nodes: <%=t.nodes.count%></div>
  <html>
  
<% end %>



</html>

</body>

app/views/trails/show.html.erb
<header>

</header>

<div class="row py-3">
  <div class="col-2"></div>
  <div class="col-8 bg-light rounded" >
      <h2>
        <div class="row d-flex justify-content-center"><%= @trail.name %></div>
      </h2>
    
      <div class="d-flex justify-content-center">
        <progress class="progress" style="height: 25px; width: 400px; "value="<%=@trail_progress%>" max="<%=@trail.nodes.count%>">

        </progress>
        </div>
      <div class="row d-flex justify-content-center">Progress: <%= @trail_progress%> / <%= @trail.nodes.count%></div>
      <div class="row d-flex justify-content-center">
        <h4>
         
        </h4>
      </div>
      
      <div class="row d-flex justify-content-center p-4"><body>


          <question>
          <h3>
          <% if @current_node %> 
            <%= @current_node.question%>
          </question>
          </h3>
          



          <% if current_user.admin %>
            <div> Answer: </div>
            <%= @current_node.answer %>
          <% end %>

          <main>
          <section class="image-section">
            <img src="" id="image" />
          </section>

        

        <% if @current_node.hint %>
          <nodehint>
            <img id="node-hint" <img style="max-width: 200px;"src="<%= @current_node.hint %>" class="hidden" />
          </nodehint>
          <button type="button" id="show-hint-button">Hint</button> 
        <% end %>


        

          

              <div class="row d-flex justify-content-center">
              
              <div>
                <%= form_with url: check_answer_path, local: true do |f| %>
                <%= f.label :answer %>
                <% if @current_node.image_question %>
                  <% if params[:answer] %>
                    <%= f.hidden_field :answer, value: params[:answer] %>
                    <img src="/images/<%= current_user.id %>.jpg" />
                  <% else %>
                    <%= f.file_field :image_answer %>
                  <% end %>
                <% else %>
                  <%= f.text_field :answer %>
                <% end %>

                <%= f.hidden_field :node_id, value: @current_node.id %>

                <%= f.submit %>
              <% end %>
              </div>
            </div>


        <% else %>
          <div class="row d-flex justify-content-center">You've completed the trail!</div>
            </div>
        <% end %>


        </body></div>
              
              
          <div class="col-2"></div>
        </div> 
        <div class="d-flex justify-content-center">
          <!-- Content here -->

          
</div> 






<script>
document.getElementById("show-hint-button").addEventListener("click", function() {
  document.getElementById("node-hint").classList.remove("hidden");
});
</script>