config/routes.rb
Rails.application.routes.draw do
get "signup", to: "users#new", as: "signup"
get "login", to: "sessions#new", as: "login"
get "logout", to: "sessions#destroy", as: "logout"

  resources :users
  get "/sessions/current", to: "sessions#destroy"
  
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/trails", to: "trails#index"
  get "/trails/:trail_id", to: "trails#show", as: "trail"
  post "/nodes/check_answer", to: "nodes#checkanswer", as: "check_answer"
  
  root "trails#index"

  get "/admin/trails", to: "trails#admin_index", as: "admin"
  get "/admin/trails/:trail_id", to: "trails#admin_show", as: "admin_show"
  post "/admin/trails", to: "trails#trail_create", as: "trail_create"
  get "/admin/trails/nodes/:node_id", to: "nodes#destroy", as: "node_destroy"

  get "admin/update/:trail_id", to: "trails#admin_show_update", as: "admin_show_update"
  post "admin/update/:trail_id", to: "nodes#update", as: "node_update" 


  post "/admin/trails/:trail_id", to: "trails#node_create", as: "node_create"


   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
 
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <title>Hiddenworld</title>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>







    <header>
      
      

  
  <body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="">Hiddn.World</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex justify-content-between collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=root_url%>" href="">Home</a>
        </li>
        <% if current_user %>
        <li class="nav-item">
          <a class="nav-link " href="<%=logout_path%>">Log Out</a>
        </li>
        <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%=signup_path%>">Sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=login_path%>">Log In</a>
        </li>
        <%end%>

        <% if current_user && current_user.admin %>
            <li class="nav-item">
            <a class="nav-link" href="<%=admin_path%>">Admin</a></a>
        </li>
        <%end%>
      </ul>
      <span class="navbar-text mr-auto">
      <%if current_user%>
        Logged in as <%= current_user.email %>.
        <%end%>
      </span>
    </div>
  </div>
</nav>

<% flash.each do |type, msg| %>
      <div class="alert alert-primary" <%= type %>"><%= msg %></div>
      <% end %>

       
         
      </ul>
        
      </nav>

    </header>    

  </body>
      

  <body style="padding-top:24px">
    <%= yield %>
     
  </body>
</html>